apiVersion: v1
kind: PersistentVolume
metadata:
  name: csnoservice-pv
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem  
  accessModes:
    - ReadWriteOnce  
  storageClassName: manual
  hostPath:
    path: "/home/railtelhrit/snomed"
