apiVersion: v1
kind: PersistentVolume
metadata:
  name: csnoservice-pv
spec:
  capacity:
    storage: 90Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  storageClassName: manual
  hostPath:
    path: "/data/snomed"
